version: '3'
services:
  instareels:
    image: moulabi1911/instareels:latest
    ports:
      - "89:80"
    deploy:
      replicas: 3

  instaphotos:
    image: moulabi1911/instaphotos:latest
    ports:
      - "86:80"
    deploy:
      replicas: 3

  instastory:
    image: moualabi1911/instastory:latest
    ports:
      - "87:80"
    deploy:
      replicas: 3
      
  instacalls:
    image: moulabi1911/instacalls:latest
    ports:
      - "88:80"
    deploy:
      replicas: 3
