version: '3'
services:
  instagramreels:
    image: moulabi1911/instagramreels:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  instagramphotos:
    image: moulabi1911/instagramphotos:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  instagramstory:
    image: moualabi1911instagramstory:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
