version: '3'
services:
  instareels:
    image: moulabi1911/instareels:latest
    ports:
      - "51:80"
    deploy:
      replicas: 3

  instaphotos:
    image: moulabi1911/instaphotos:latest
    ports:
      - "52:80"
    deploy:
      replicas: 3

  instastory:
    image: moualabi1911/instastory:latest
    ports:
      - "53:80"
    deploy:
      replicas: 3
      
  instacalls:
    image: moulabi1911/instacalls:latest
    ports:
      - "54:80"
    deploy:
      replicas: 3
